agenda/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


admin.site.site_header = "Agendamento de Horários"
admin.site.index_title = 'LavaCar - Agendamento de Horários'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('fornecedores.urls')),
    path('', include('clientes.urls')),
    path('', include('produtos.urls')),
    path('', include('funcionarios.urls')),
    path('', include('servicos.urls')),
    path('', include('servicos.urls')),
    path('', include('agendamentos.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



home/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import path, reverse_lazy

from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(template_name='login.html', extra_context={'titulo': 'Autenticação'}), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('alterar_senha/', PasswordChangeView.as_view(
        template_name='login.html',
        extra_context={'titulo': 'Alterar senha'},
        success_url=reverse_lazy('index')
    ), name='alterar_senha'),
]

servicos/urls.py
from django.urls import path
from .views import ServicosView, ServicoAddView, ServicoUpdateView, ServicoDeleteView, ServicoInLineEditView

urlpatterns = [
    path('servicos', ServicosView.as_view(), name='servicos'),
    path('servico/adicionar/', ServicoAddView.as_view(), name='servico_adicionar'),
    path('<int:pk>/servico/editar/', ServicoUpdateView.as_view(), name='servico_editar'),
    path('<int:pk>/servico/apagar/', ServicoDeleteView.as_view(), name='servico_apagar'),
    path('<int:pk>/servico/inline', ServicoInLineEditView.as_view(), name='servico_inline'),

]

servicos/models.py
from django.db import models
from django.db.models.functions import Upper


class Servico(models.Model):
    nome = models.CharField('Nome', max_length=100, help_text='Nome completo do serviço', unique=True)
    preco = models.DecimalField('Preço', max_digits=5, decimal_places=2, help_text='Preço do serviço')
    descricao = models.TextField('Descrição', max_length=300, help_text='Descrição e observações do serviço')
    produto = models.ManyToManyField(to='produtos.Produto', through='servicos.ProdutosServico')

    @property
    def produtos(self):
        return ProdutosServico.objects.filter(servico=self)

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'
        ordering = [Upper('nome')]

    def __str__(self):
        return self.nome


class ProdutosServico(models.Model):
    servico = models.ForeignKey(
        'servicos.Servico',
        verbose_name='Serviço',
        help_text='Nome do serviço realizado',
        on_delete=models.CASCADE,
        related_name='servico'
    )
    produto = models.ForeignKey(
        'produtos.Produto',
        verbose_name='Produto',
        help_text='Nome do produto utilizado',
        on_delete=models.PROTECT,
        related_name='produto'
    )
    quantidade = models.DecimalField(
        verbose_name='Quantidade',
        max_digits=5,
        decimal_places=2,
        help_text='Quantidade utilizada de produto'
    )

    class Meta:
        verbose_name = 'Produto utilizado'
        verbose_name_plural = 'Produtos utilizados'

    def __str__(self):
        return f'{self.produto}'

servicos/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Servico
from .models import Servico, ProdutosServico


class ServicoModelForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = ['nome', 'descricao', 'preco']

        error_messages = {
            'nome': {'required': 'O nome do serviço é um campo obrigatório', 'unique': 'Serviço já cadastrado'},
            'descricao': {'required': 'A descrição do serviço é um campo obrigatório'},
            'preco': {'required': 'O preço do serviço é um campo obrigatório'},
        }


ProdutosServicoInLine = inlineformset_factory(
    Servico, ProdutosServico, fk_name='servico',
    fields=('produto', 'quantidade'), extra=1, can_delete=True
)

servicos/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q, ProtectedError
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib import messages
from django.views.generic.base import TemplateResponseMixin

from servicos.forms import ServicoModelForm, ProdutosServicoInLine
from servicos.models import Servico


class ServicosView(PermissionRequiredMixin,ListView):
    permission_required = 'servicos.delete_servicos'
    permission_denied_message = 'ver servicos'

    model = Servico
    template_name = 'servicos.html'

    def get_queryset(self):
        buscar = self.request.GET.get('buscar')
        qs = super(ServicosView, self).get_queryset()

        if buscar:
            qs = qs.filter(Q(nome__icontains=buscar) | Q(descricao__icontains=buscar))

        if qs.count() > 0:
            paginator = Paginator(qs, per_page=1)
            listagem = paginator.get_page(self.request.GET.get('page'))
            return listagem
        else:
            messages.info(self.request, 'Não existem serviços cadastrados!')
            return qs.none()  # Retorna queryset vazio para evitar erros


class ServicoAddView(PermissionRequiredMixin,SuccessMessageMixin, CreateView):
    permission_required = 'servicos.add_servicos'
    permission_denied_message = 'add servicos'

    model = Servico
    form_class = ServicoModelForm
    template_name = 'servico_form.html'
    success_url = reverse_lazy('servicos')
    success_message = 'Serviço cadastrado com sucesso!'


class ServicoUpdateView(PermissionRequiredMixin,SuccessMessageMixin, UpdateView):
    permission_required = 'servicos.update_servicos'
    permission_denied_message = 'att servicos'

    model = Servico
    form_class = ServicoModelForm
    template_name = 'servico_form.html'
    success_url = reverse_lazy('servicos')
    success_message = 'Serviço alterado com sucesso!'


class ServicoDeleteView(PermissionRequiredMixin,SuccessMessageMixin, DeleteView):
    permission_required = 'servicos.delete_servicos'
    permission_denied_message = 'del servicos'

    model = Servico
    template_name = 'servico_apagar.html'
    success_url = reverse_lazy('servicos')
    success_message = 'Serviço apagado com sucesso!'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        try:
            return super().post(request, *args, **kwargs)
        except ProtectedError:
            messages.error(request,
                           message=(
                               f'O serviço {self.object} não pode ser excluído. '
                               f'Esse serviço está registrado em ordens de serviço'
                           )
                           )
        finally:
            return redirect(success_url)


class ServicoInLineEditView(TemplateResponseMixin, View):
    template_name = 'servico_form_inline.html'

    def get_formset(self, data=None):
        return ProdutosServicoInLine(instance=self.servico, data=data)

    def dispatch(self, request, *args, **kwargs):
        self.servico = get_object_or_404(Servico, id=kwargs.get('pk'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response({'servico': self.servico, 'formset': formset})

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('servicos')
        return self.render_to_response({'servico': self.servico, 'formset': formset})


# slide 15<

servicos/templates/servico_apagar.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="card shadow m-3 col-md-6 mx-auto">
        <div class="card-body">
            <div class="row">
                <h3 class="text-center">Dados do Serviço</h3>
                <p class="p-2 mt-2"><strong>Nome: </strong>{{ object.nome }}</p>
                <p class="p-2 mt-2"><strong>Descrição: </strong>{{ object.descricao }}</p>
                <p class="p-2 mt-2"><strong>Preço: </strong>{{ object.preco }}</p>
                <p class="p-2 mt-2">Confirma a exclusão do serviço: <strong>{{ object }}</strong>?</p>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <div class="text-end">
                        {% bootstrap_button button_type="submit" content="Sim" %}
                        <a href="{% url 'servicos' %}" class="btn btn-secondary text-white" type="button">
                            <span class="text">Cancelar</span>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

servicos/templates/servico_form.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="card shadow m-3 col-md-6 mx-auto">
    <div class="card-body">
        <div class="row">
            <h3 class="text-center">Cadastro de serviço</h3>
            <form method="POST" enctype="multipart/form-data">

                {% csrf_token %}
                {% bootstrap_form form %}

                <div class="text-end">
                    {% bootstrap_button button_type="submit" content="Salvar" %}
                    <a href="{% url 'servicos' %}" class="btn btn-secondary text-white" type="button">
                        <span class="text">Cancelar</span>
                    </a>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

servicos/templates/servico_form_inline.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="card shadow m-3 col-md-6 mx-auto">
    <div class="card-body">
        <div class="row">
            <h3 class="text-center">Produtos utilizados no serviço {{ servico }}</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_formset formset layout='horizontal' %}
                {{ formset.management_form }}
                <div class="text-end">
                    {% bootstrap_button button_type="submit" content="Salvar" %}
                    <a href="{% url 'servicos' %}" class="btn btn-secondary text-white" type="button">
                        <span class="text">Cancelar</span>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

servicos/templates/servicos.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
    <section class="section">
        <div class="container">
            <form action="" method="GET">
                <div class="form-group row p-3">
                    <label class="col-sm-2 col-form-label">Nome ou descrição do serviço: </label>
                    <div class="col-sm-8">
                        <input class="form-control" type="text" name="buscar" value="{{ request.GET.buscar }}"
                               placeholder="Digite o nome ou a descrição do serviço">
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary">
                            Buscar
                        </button>
                    </div>
                </div>
            </form>
            {% if object_list %}
                <div class="card-body">
                    <h3 class="text-center">Serviços Cadastrados</h3>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-success">
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Preço</th>
                                <th>Produtos</th>


                                <th style="width: 100px; text-align: center">Ações</th>
                            </thead>
                            <tbody>
                               {% for servico in object_list %}
                                    <tr>
                                        <td> {{ servico.nome }}  </td>
                                        <td>    {{ servico.descricao }}  </td>
                                        <td>   {{ servico.preco }}   </td>
                                        <td>
                                            {% for produto in servico.produtos %}
                                                {% if forloop.last %}
                                                    {{ produto }}
                                                {% else %}
                                                    {{ produto }},
                                                {% endif %}
                                            {% endfor %}
                                        </td>


                                        <td style="text-align: center">
                                            {% if perms.servicos.add_produtosservico %}

                                             <a href="{% url 'servico_inline' servico.pk %}">
                                                    <span class="icon">
                                                        <i class="fas fa-flask"></i>
                                                    </span>
                                                </a>

                                            {% endif %}

                                            <a href="{% url 'servico_editar' servico.pk %}">
                                                <span class="icon">
                                                    <i class="fas fa-edit"></i>
                                                </span>
                                            </a>
                                            <a href="{% url 'servico_apagar' servico.pk %}">
                                                <span class="icon">
                                                    <i class="far fa-trash-alt"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center">
                                {% bootstrap_pagination object_list url="/servicos?page=1" size="sm" %}
                        </div>
                    </div>

                </div>
            {% endif %}
        </div>
    </section>
{% endblock %}